"""role user add

Revision ID: 2fd1c12449be
Revises: 78710608f053
Create Date: 2026-09-20 18:44:17.155563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd1c12449be'
down_revision: Union[str, Sequence[str], None] = '78710608f053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('PATIENT', 'PROFESSIONAL', 'ADMIN', name='userrole'), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
